create extension if not exists "pgcrypto";

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  visibility text not null default 'open' check (visibility in ('open', 'secret')),
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  sender_name text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists messages_room_id_created_at_idx
  on public.messages (room_id, created_at asc);

do $$
begin
  alter publication supabase_realtime add table public.rooms;
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end
$$;

ALTER TABLE public.rooms ADD COLUMN IF NOT EXISTS passcode TEXT;


alter table public.rooms add column if not exists owner_name text;

-- messages 테이블 RLS 비활성화 (또는 정책 추가)
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms DISABLE ROW LEVEL SECURITY;

-- rooms: 누구나 읽기/쓰기
CREATE POLICY "allow_all_rooms" ON public.rooms FOR ALL TO anon USING (true) WITH CHECK (true);

-- messages: 누구나 읽기/쓰기  
CREATE POLICY "allow_all_messages" ON public.messages FOR ALL TO anon USING (true) WITH CHECK (true);

ALTER TABLE public.messages
ADD COLUMN IF NOT EXISTS is_system boolean NOT NULL DEFAULT false;