create extension if not exists "pgcrypto";

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  sender_name text not null,
  content text not null,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists messages_room_id_created_at_idx
  on public.messages (room_id, created_at asc);

do $$
begin
  alter publication supabase_realtime add table public.rooms;
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end
$$;
